version: "3.9"

services:
  backend:
    container_name: name
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./home:/app
    ports:
      - "3001:3001"
    command:
      "pnpm start"